### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by AxelHoss** [bkbilly/mqtt_fingerprint_pi#2]
instead 
`git clone git@github.com:bkbilly/mqtt_fingerprint_pi.git /opt/mqtt_fingerprint_pi`

use

`git clone https://github.com/bkbilly/mqtt_fingerprint_pi /opt/mqtt_fingerprint_pi`

**Comment by bkbilly** [comment]
I can't say that it's wrong. Both commands work as expected. 
Do you have issues with this implementation?

**Comment by AxelHoss** [comment]
on the second command not :-)
Maybe u can note that somewhere. 

I got one other question. I want to use your code on a other mqtt broker (not ha). 
How can i set the mode to enroll, delete etc over mqtt?

**Comment by bkbilly** [comment]
You can read all the supported commands on [README](https://github.com/bkbilly/mqtt_fingerprint_pi#mqtt-commands).

I would like for you to send me the output of the 1st command. It seems really strange that it doesn't work for you.

**Comment by AxelHoss** [comment]
Error was:
`Permission denied (publickey).`

**Comment by bkbilly** [comment]
Fixed on the newest commit.
