### ISSUE TITLE
Customized finger topic

### ISSUE THREAD

**Issue by AxelHoss** [bkbilly/mqtt_fingerprint_pi#6]
Hi, is there a way to customize the finger topic? I got two r503 and want to connect to the same mqtt server.

**Comment by AxelHoss** [comment]
when im trying to connect with an additional pi the second pi wont work. Theres also no led working. Do you know why?

**Comment by bkbilly** [comment]
I've just added support for changing the default topic.
You will need to add to your config.yaml file this option `topic: "fingerprint"`.

As for your led not working, I don't know what could be the issue...

**Comment by AxelHoss** [comment]
Hi @bkbilly  thanks for your help. Your update with the new topic is great. Now my server gets customized messages. The led is now also working. 
But i have still the issue that when two PIs are connected to the same mqtt server, only one of them send mqtt messages. When i disconnect the working PI, the second PI is then working. Is there a log to read the mqtt messages? The finger is found because i see the blue light..

EDIT: Maybe its a Paho Mqtt issue. Can i edit my client id?

**Comment by AxelHoss** [comment]
paho mqtt seems not allow several clients ids:
https://stackoverflow.com/questions/40548730/two-paho-mqtt-clients-subscribing-to-the-same-client-localy

But could this be a solution?
http://www.steves-internet-guide.com/multiple-client-connections-python-mqtt/

**Comment by bkbilly** [comment]
Normally Paho MQTT creates the client_id automatically. 
It might be a bug on the version that I was using because I've used multiple paho mqtt clients before without any issues.

I've pushed a new update which I've upgraded all the libraries to their latest version.
You must do a manual upgrade of the libraries: 
```bash
pip install -U -r requirements.txt
```

Hopefully this will fix your issue with the two devices.

PS: If you want to see the MQTT messages that are published, you could try the app [MQTT Explorer](https://mqtt-explorer.com/).

**Comment by AxelHoss** [comment]
i've added a third Pi with an R503 and your app. Same issue. Only one of them is working. But i guess this could be an mqtt server error. I will set up an mqtt server lxc and test it.

**Comment by AxelHoss** [comment]
it is a mqtt server issue. If im setup several servers its working great. So you can close this issue. Thanks for your help

**Comment by bkbilly** [comment]
Happy to help, but could you explain what was the issue with the mqtt broker?

**Comment by AxelHoss** [comment]
If there are more than one pi with mqtt Client is connected, my server respond just to the last connected client. Dont know why. Im using iobroker as home system. Maybe they can help me in the future. But for now its ok
